FROM ghcr.io/p-fruck/netconf-container-tools/libyang
ARG netconf_version=v3.5.1

RUN dnf install -y libnetconf2-devel libssh-devel openssl-devel libcurl-devel
RUN git clone https://github.com/CESNET/libnetconf2 -b ${netconf_version}

WORKDIR /app/libnetconf2
RUN cmake . && make install

WORKDIR /app
